% KNN 
% author Yixing Liu
% created on October 17,2015
% last updated on October 18,2015
% description: this can be used as a KNN template. 
% Change the training_matrix, training_label and K value to build your own
% knn model.

% load data generated by Richmond
training_matrix = [subject1_xyz; subject3_xyz; subject5_xyz];
training_label = [subject1_label; subject3_label;subject5_label];
testing_matrix = [subject2_xyz; subject4_xyz];
testing_label = [subject2_label; subject2_label];

knn_model = fitcknn(training_matrix,training_label,'NumNeighbors',80);
rloss = resubLoss(knn_model) % this means it predicts 29.72% of the training data incorrectly
% construct a cross-validated classifier from the model
cv_model = crossval(knn_model,'kfold',5);
kloss = kfoldLoss(cv_model) % this means it predicts 30.64% of the training data incorrectly
count = 0;
label = predict(knn_model, testing_matrix);
for i = 1:3136
    if(label(i) ~= testing_label(i))
        count = count + 1;
    end
end
count/3136
% KNN of raw data giving us an 56% accuracy means that data are seperable.
