%% SVM classification template
% author Yixing Liu
% created on October 17,2015
% last updated on October 19,2015
% environment: mac x64, windows x64

p = mfilename('fullpath');
codeDirectory = fileparts(p);
addpath([codeDirectory '/feature_handles']);
addpath([codeDirectory '/liblinear-2.1']);
addpath([codeDirectory '/liblinear-2.1/matlab']);
addpath(genpath([codeDirectory '/feature_handles']));

% add path to use the SVM library
addpath('liblinear-2.1/matlab')
% load data generated by Richmond
load('subject_data.mat');

% you can design your own training_matrix, training_label,
% testing_matrix, testing_label here
handle{1} = @abs_average_peak_handle;
handle{2} = @abs_std_handle;
handle{3} = @abs_fft_skewness_handle;
handle{4} = @rms_handle;
weights = [1, 0.5, 0.25, 0.75];

% According to Richmond, mean of abs and RMS gives the best visualization
%   FROM RICHMOND: mean of abs and RMS are essentially the same feature,
%   maybe we shouldn't use both.
%   Also, I included action[1-4]_xyz in subject_data.mat, you don't need to
%   create them.
% so I use mean of abs and RMS as examples here
action1_xyz = [action1(:,2),action1(:,3),action1(:,4)];
action2_xyz = [action2(:,2),action2(:,3),action2(:,4)];
action3_xyz = [action3(:,2),action3(:,3),action3(:,4)];
action4_xyz = [action4(:,2),action4(:,3),action4(:,4)];

training_matrix1 = extract_features_tester(action1_xyz, 50, 50, handle, weights);
training_matrix2 = extract_features_tester(action2_xyz, 50, 50, handle, weights);
training_matrix3 = extract_features_tester(action3_xyz, 50, 50, handle, weights);
training_matrix4 = extract_features_tester(action4_xyz, 50, 50, handle, weights);
training_matrix = [training_matrix1; training_matrix2; training_matrix3; training_matrix4];
training_label = [ones(size(training_matrix1,1),1); 2*ones(size(training_matrix2,1),1); 3*ones(size(training_matrix3,1),1);4*ones(size(training_matrix4,1),1)];

% type keyword train to look up parameters of train
% predict parameters should be consistent with train parameters
svm_model = train(training_label, sparse(training_matrix),'-s 2');
% in principle we should seperate training set and testing set
testing_label = training_label;
testing_matrix = training_matrix;
[predicted_label] = predict(training_label, sparse(training_matrix), svm_model);
